### ISSUE TITLE
Cashe

### ISSUE THREAD

**Issue by yzhyyyyy** [Tandhjulet/SkEssentials#1]
Hvis man bruger `"%cache stored as ""cba""%"` virker det fint, men hvis nu man bruger `"%cache stored as ""cba.%player%""%"` kommer den med denne fejl:
![image](https://user-images.githubusercontent.com/96750444/165368675-cd44512d-83dd-4891-be90-53a43c7bf619.png)

**Comment by Tandhjulet** [comment]
Dette er ikke en fejl med pluginnet, derimod er der en fejl med dit skript.
Du har alt for mange nests, hvilket gør at skript ikke kan læse syntaksen. Prøv at dele det op, f.eks sådan her:

`set {_} to "abcd.%player%"`
`send "%cache stored as {_}%"`
